"""empty message

Revision ID: 0301d2b9206c
Revises: 621de38aa48a
Create Date: 2022-04-24 13:04:27.515600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0301d2b9206c'
down_revision = '621de38aa48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipos_vacinas', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tipos_vacinas', 'cat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipos_vacinas', 'cat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tipos_vacinas', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
