"""empty message

Revision ID: 192caf019c7b
Revises: 
Create Date: 2022-04-18 08:54:02.906692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192caf019c7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clientes',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=14), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=False),
    sa.Column('is_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raca', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_vacinas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('data_aplicacao', sa.Date(), nullable=True),
    sa.Column('data_revacinacao', sa.Date(), nullable=True),
    sa.Column('is_pupies', sa.Boolean(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_vacinas')
    op.drop_table('pets')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
